"""
Build the committed data bundle the dashboard ships with.

The dashboard reads its data from the git-ignored working `results/` tree. So a
fresh clone can run it without that tree, this script copies the small derived
files the dashboard needs into `dashboard/data/`, mirroring the repository's
data layout. The dashboard loader (`lib/data.py`) prefers this bundle and falls
back to the working tree when developing.

Only the files the dashboard actually reads are copied. The large solved
networks (`*.nc`, 170 MB to 1.1 GB) and the heavy nodal CSVs
(`consumption_intensity.csv`, `generation_intensity.csv`) are deliberately
excluded; the bundle is about 30 MB.

Run from the repository root after (re)generating the dashboard data:
    python dashboard/build_data_bundle.py
"""
from __future__ import annotations

import shutil
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
BUNDLE = REPO / "dashboard" / "data"

TOPOLOGIES = ["zonal_17bus", "reduced_32bus", "reduced_32bus_copperplate",
              "etys_2000bus"]

# Per-topology files the dashboard reads. Missing files are skipped (e.g. the
# copperplate has no per-bus map), so the list can be a superset.
PER_TOPOLOGY = [
    "system_carbon_intensity.csv",
    "hourly_generation_by_carrier.csv",
    "hourly_emissions_by_carrier.csv",
    "generation_by_carrier.csv",
    "buses_with_ci.csv",
    "bus_carrier_generation.csv",
    "bus_carrier_emissions.csv",
    "neso_region_intensity.csv",
    "region_carrier_generation.csv",
    "region_carrier_emissions.csv",
    "bus_catchments.geojson",
    "manifest.json",
]

# Per-topology files that live outside results/ (repo-relative template, {dir}
# is the topology directory name). Missing files are skipped.
PER_TOPOLOGY_EXTRA = [
    "data/topology/{dir}/catchment_names.csv",
]

# Shared files (repo-relative paths).
SHARED = [
    "results/neso_2023/national_intensity.csv",
    "results/neso_2023/factors.json",
    "data/topology/neso_regions.geojson",
]


def copy(rel: str, log: list) -> None:
    src = REPO / rel
    if not src.exists():
        return
    dst = BUNDLE / rel
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    log.append((rel, dst.stat().st_size))


def main() -> None:
    if BUNDLE.exists():
        shutil.rmtree(BUNDLE)
    copied: list = []
    for topo in TOPOLOGIES:
        for fname in PER_TOPOLOGY:
            copy(f"results/2023_topology_default/{topo}/{fname}", copied)
        for tmpl in PER_TOPOLOGY_EXTRA:
            copy(tmpl.format(dir=topo), copied)
    for rel in SHARED:
        copy(rel, copied)

    total = sum(sz for _, sz in copied)
    print(f"Bundle written to {BUNDLE}")
    print(f"  {len(copied)} files, {total / 1e6:.1f} MB total")
    missing_topos = [t for t in TOPOLOGIES
                     if not (BUNDLE / "results" / "2023_topology_default" / t
                             / "system_carbon_intensity.csv").exists()]
    if missing_topos:
        print(f"  WARNING: no system_carbon_intensity.csv bundled for: "
              f"{missing_topos} (regenerate the working data first)")
    # A small marker so the bundle's provenance is obvious in the repo.
    (BUNDLE / "README.md").write_text(
        "# Dashboard data bundle\n\n"
        "Auto-generated by `dashboard/build_data_bundle.py`. These are the "
        "pre-computed files the dashboard reads, copied from the git-ignored "
        "working `results/` tree so a fresh clone runs without it. Do not edit "
        "by hand; regenerate with the build script. Large solved networks "
        "(`*.nc`) and nodal CSVs are intentionally excluded.\n",
        encoding="utf-8")


if __name__ == "__main__":
    main()
